# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'wedding-wx0zmr9djq'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'The Reception', url: 'reception'} 
- {name: 'Comments', url: 'comments'} 
# - {name: 'Information', url: 'qna'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
- {name: 'Contact', url: 'rsvp'} 
# - {name: 'Contact',            url: 'contact'}

# # Available social icons are powered by Font Awesome, so you can use any icon that they offer
# social:
# - {icon: 'twitter', link:    'https://twitter.com/SimonBesson'}
# - {icon: 'instagram', link:  'https://instagram.com/9picogram'}
# - {icon: 'github', link: 'https://github.com/shamansim'}
# #- {icon: 'envelope', link:   'mailto:contact@paulle.ca'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# # Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'
site:
  hide_post_share: "true"
  hide_related_posts: "true"

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'Other sections...'

post_date_prefix: 'Last update on'
